# main menu navigation
menu:
  Home: /
  About: /about 
  # Archive: /archives 

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  zhihu: people/wu-hua-rong-18
  github: wufan123

user:
  name: wufan
  avatar: /images/avatar.jpg
  location: 福建厦门
  # email: 357114638@qq.com
  description: 357114638@qq.com
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc: 
  enable: true 
  repo: wufan123/wufan123.github.io # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId: 4lVndPEgYCJcGVK0eyws4kyz-gzGzoHsz
  appKey: pG0IL7uEfmLFB0miT5zUcCko

comment_disqus:
    enable: false
    url:  # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set 
appearance: light # Default value is auto

# Miscellaneous
favicon: /images/favicon.png

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id: 1440a68a4b8e8906f338cb023aeef906

# picture of about page
about_pic: /images/about2.webp
